services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${PGTZ}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./suwmp_be/postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      waste-collect-net:

networks:
  waste-collect-net:
      driver: bridge

volumes:
  postgres-data: